### ISSUE TITLE
PEMS-BAY

### ISSUE THREAD

**Issue by trinayan** [chnsh/DCRNN_PyTorch#10]
Hi,

Thanks for the great work.

I am sort of confused if for running the pems-bay dataset, I need to do have more files. Specifically the data/sensor_graph seems to be present for the LA dataset but not for BAY dataset. So to train on the BAY dataset, what are the additional steps to be taken?. Thank you

**Comment by yuqirose** [comment]
@liyaguang

**Comment by liyaguang** [comment]
@trinayan  the sensor graph files for the PEMS-BAY can be found at: https://github.com/liyaguang/DCRNN/tree/master/data/sensor_graph

Also the instructions for training in available at: https://github.com/liyaguang/DCRNN#model-training

**Comment by assemgul-kozhabek** [comment]
Is there map with location of all sensors? I have seen as an image but I need it in usable format for simulation.
Thank you in advance!

**Comment by yuqirose** [comment]
> Is there map with location of all sensors? I have seen as an image but I need it in usable format for simulation.
> Thank you in advance!

they are in latitude/longitude format. You can view it by mapping the lat/lon to google map.
