### ISSUE TITLE
Double sigmoid inside RNNCell

### ISSUE THREAD

**Issue by razvanc92** [chnsh/DCRNN_PyTorch#12]
I was looking at the implementation of the DCGRUCell, and I've spotted something out of order. If we are using 'fc' for  U and R gates we are going to apply the sigmoid twice (line 121 and  96). Is this how it's intended to work, or is there a bug?

**Comment by yuqirose** [comment]
could you share a screenshot?

**Comment by razvanc92** [comment]
@yuqirose Sure. If we look at the following image on line 96 the value is sigmoid(fn(...)). 


![ss1](https://user-images.githubusercontent.com/5858617/104640869-575b6000-56a9-11eb-80f3-a39c6c80bb2e.png)

Now if we look at the next picture (line 121) we are applying again sigmoid. 
![ss2](https://user-images.githubusercontent.com/5858617/104641061-92f62a00-56a9-11eb-9545-46fb6c7e0139.png)

Am I missing something?

**Comment by yuqirose** [comment]
@razvanc92  line 121 is applied to W*x, line 96 is applied to f(W*x) + b

**Comment by razvanc92** [comment]
@yuqirose Thank you for your replay. Following the code we are doing sigmoid(sigmoid(Wx) + b) which is different from the original implementation of GRU  which uses sigmoid(Wx +b).
