### ISSUE TITLE
The formulation of Diffusion Convolution is wrong

### ISSUE THREAD

**Issue by hazdzz** [chnsh/DCRNN_PyTorch#14]
In DCRNN, there is no diffusion process in the graph, because we cannot find any restart probability alpha in the code. Here, I offer a correct Diffusion Matrix as below:

![GDC(PPR)](https://user-images.githubusercontent.com/11409688/105697996-4085fa80-5f40-11eb-9ff5-3bdcf9adcb17.png)

**Comment by yuqirose** [comment]
The probabilities are absorbed into the trainable weights in the neural networks.
