### ISSUE TITLE
CUDA out of memory error

### ISSUE THREAD

**Issue by mdanb** [chnsh/DCRNN_PyTorch#6]
When I run `python dcrnn_train_pytorch.py --config_filename=data/model/dcrnn_la.yaml` I get the error 
`RuntimeError:CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 5.80 GiB total capacity; 4.36 GiB already allocated; 6.69 MiB free; 4.63 GiB reserved in total by PyTorch)`

**Comment by chnsh** [comment]
You should reduce the batch size and try again - this isn't really an issue with the repository
