### ISSUE TITLE
About the performance improvement compared with Tensorflow implementation

### ISSUE THREAD

**Issue by LiFXe** [chnsh/DCRNN_PyTorch#9]
Hi, thank you for the implementation very much, it helps me a lot! BTW, I am really confused about the performance improvement comparing the PyTorch implementation with the original Tensorflow implementation. I would be very grateful if you could give me some guidance, thank you in advance！

**Comment by yuqirose** [comment]
What is your confusion? Could you elaborate your questions?

**Comment by LiFXe** [comment]
> What is your confusion? Could you elaborate your questions?
This Pytorch implementation performs much better than the original Tensorflow implementation in MAE and other metrics, I am really confused about this.

**Comment by yuqirose** [comment]
https://github.com/chnsh/DCRNN_PyTorch/issues/3#issuecomment-655684405
